In [1]:
# Importing the most important library numpy
# Numpy is preffered over python lists since most of its implementations are faster (the functions are tied closer with hardware)
import numpy as np

### Run the following to grasp the basics of numpy

In [2]:
# 1D array
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Array of zeros
zeros = np.zeros((2, 3))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((3, 2))
print("Ones Array:\n", ones)

# Array with a range of values
range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)

# Array with equally spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_arr)

# Random array
random_arr = np.random.rand(3, 3)  # Uniform distribution
print("Random Array:\n", random_arr)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Random Array:
 [[0.50386617 0.01837637 0.76003643]
 [0.51745631 0.61187231 0.92911749]
 [0.47218305 0.59359252 0.47300759]]


In [3]:
# In a numpy array, all the elements must be homogenous (of the same data type)
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # Dimensions
print("Size:", arr.size)  # Total number of elements
print("Data Type:", arr.dtype)  # Type of elements
print("Number of Dimensions:", arr.ndim)  # Number of dimensions

Shape: (2, 3)
Size: 6
Data Type: int32
Number of Dimensions: 2


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, Column 1

# Slicing
print("First row:", arr[0, :])  # All columns of the first row
print("First column:", arr[:, 0])  # All rows of the first column
print("Subarray:\n", arr[0:2, 1:3])  # Rows 0-1 and Columns 1-2

Element at [0, 1]: 2
First row: [1 2 3]
First column: [1 4]
Subarray:
 [[2 3]
 [5 6]]


In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

# Broadcasting
scalar = 2
print("Multiply by scalar:", arr1 * scalar)

# Mathematical functions
print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Multiply by scalar: [2 4 6]
Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape
reshaped = arr.reshape((3, 2))
print("Reshaped Array:\n", reshaped)

# Transpose
transposed = arr.T
print("Transposed Array:\n", transposed)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking
stacked = np.vstack((arr1, arr2))  # Vertical stack
print("Stacked Vertically:\n", stacked)

hstacked = np.hstack((arr1, arr2))  # Horizontal stack
print("Stacked Horizontally:", hstacked)

# Splitting
split = np.split(arr2, 3)  # Split into 3 parts
print("Split Array:", split)

Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally: [1 2 3 4 5 6]
Split Array: [array([4]), array([5]), array([6])]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean indexing
even = arr[arr % 2 == 0]
print("Even Numbers:", even)
# Masking is a common technique used
print("Masking:", arr % 2 == 0)

# Filtering
filtered = arr[arr > 3]
print("Numbers greater than 3:", filtered)

Even Numbers: [2 4 6]
Masking: [False  True False  True False  True]
Numbers greater than 3: [4 5 6]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Standard Deviation: 1.707825127659933


### Some assignment problems

In [10]:
# Assignment 1
'''
Create an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.
Then reshape it to a (9, 2) array and take its transpose. 
Find the locations where all elements are greater than the mean of the array and print it
'''

'\nCreate an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.\nThen reshape it to a (9, 2) array and take its transpose. \nFind the locations where all elements are greater than the mean of the array and print it\n'

In [11]:
# TODO
import numpy as np

# Step 1: Create an array of 18 random elements with shape (3, 6)
arr = np.random.rand(3, 6) * 5  # scale to roughly match your sum/mean range
print("Original array:\n", arr)

# Step 2: Add [0, 0, 2, 4, 5, 3] to each row
add_array = np.array([0, 0, 2, 4, 5, 3])
arr_added = arr + add_array
print("\nAfter adding [0,0,2,4,5,3] to each row:\n", arr_added)

# Step 3: Reshape to (9, 2)
arr_reshaped = arr_added.reshape(9, 2)
print("\nReshaped array (9,2):\n", arr_reshaped)

# Step 4: Take transpose
arr_transposed = arr_reshaped.T
print("\nTransposed array (2,9):\n", arr_transposed)

# Step 5: Calculate mean
mean_value = arr_transposed.mean()
print("\nMean of transposed array:", mean_value)

# Step 6: Find locations where all elements in a column are greater than mean
# Since we want "all elements" greater than mean, we check along axis 0 (columns)
columns_all_gt_mean = np.where((arr_transposed > mean_value).all(axis=0))[0]
print("\nColumns where all elements are greater than mean:", columns_all_gt_mean)

# Optional: print values of these columns
print("\nValues in these columns:\n", arr_transposed[:, columns_all_gt_mean])


Original array:
 [[0.16144965 2.44861897 2.43953837 2.57793022 2.67739472 3.13666849]
 [0.56812145 3.33255551 2.68775405 2.75461338 3.8910122  1.08627823]
 [3.20732134 4.68145804 2.27609023 3.69367643 3.35979052 1.52499514]]

After adding [0,0,2,4,5,3] to each row:
 [[0.16144965 2.44861897 4.43953837 6.57793022 7.67739472 6.13666849]
 [0.56812145 3.33255551 4.68775405 6.75461338 8.8910122  4.08627823]
 [3.20732134 4.68145804 4.27609023 7.69367643 8.35979052 4.52499514]]

Reshaped array (9,2):
 [[0.16144965 2.44861897]
 [4.43953837 6.57793022]
 [7.67739472 6.13666849]
 [0.56812145 3.33255551]
 [4.68775405 6.75461338]
 [8.8910122  4.08627823]
 [3.20732134 4.68145804]
 [4.27609023 7.69367643]
 [8.35979052 4.52499514]]

Transposed array (2,9):
 [[0.16144965 4.43953837 7.67739472 0.56812145 4.68775405 8.8910122
  3.20732134 4.27609023 8.35979052]
 [2.44861897 6.57793022 6.13666849 3.33255551 6.75461338 4.08627823
  4.68145804 7.69367643 4.52499514]]

Mean of transposed array: 4.916959275002

In [12]:
# Assignment 2
'''
Create an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation
(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)
'''

'\nCreate an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation\n(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)\n'

In [13]:
# TODO
# Hint use np.random.poisson

import numpy as np

# Step 1: Create a Poisson-distributed array of length 20
lam = 3.5  # Using the mean you provided
poisson_array = np.random.poisson(lam, 20)
print("Original Poisson array:\n", poisson_array)

# Step 2: Calculate mean and standard deviation
mean_val = poisson_array.mean()
std_val = poisson_array.std()
print("\nMean:", mean_val)
print("Standard Deviation:", std_val)

# Step 3: Center the array around the mean and normalize
# Centering around the mean and dividing by std
normalized_array = (poisson_array - mean_val) / std_val
print("\nCentered and Normalized array:\n", normalized_array)

# Step 4: Optional stats to verify
print("\nSum:", poisson_array.sum())
print("Maximum:", poisson_array.max())
print("Minimum:", poisson_array.min())


Original Poisson array:
 [3 5 1 2 3 5 6 3 3 2 1 1 2 4 3 4 4 2 2 2]

Mean: 2.9
Standard Deviation: 1.3747727084867523

Centered and Normalized array:
 [ 0.0727393   1.52752523 -1.38204664 -0.65465367  0.0727393   1.52752523
  2.2549182   0.0727393   0.0727393  -0.65465367 -1.38204664 -1.38204664
 -0.65465367  0.80013226  0.0727393   0.80013226  0.80013226 -0.65465367
 -0.65465367 -0.65465367]

Sum: 58
Maximum: 6
Minimum: 1
